### ISSUE TITLE
logback 添加 SMTPAppender

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-platform#11]
logback 添加 SMTPAppender

**Comment by venusdrogon** [comment]
```JAVA



03:07:20,036 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [ch.qos.logback.classic.net.SMTPAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.net.SMTPAppender
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.net.SMTPAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addStatus(StatusViaSLF4JLoggerFactory.java:32)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addInfo(StatusViaSLF4JLoggerFactory.java:20)
	at 	at ch.qos.logback.classic.servlet.LogbackServletContainerInitializer.onStartup(LogbackServletContainerInitializer.java:32)
	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5423)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at 	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: javax/mail/internet/AddressException
	at 	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2595)
	at 	at java.lang.Class.getConstructor0(Class.java:2895)
	at 	at java.lang.Class.newInstance(Class.java:354)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:61)
	at 	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.mail.internet.AddressException
	at 	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
	at 	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	at 	... 34 common frames omitted
03:07:20,039 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@16:73 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.net.SMTPAppender
	at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.net.SMTPAppender
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:76)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addStatus(StatusViaSLF4JLoggerFactory.java:32)
	at 	at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addInfo(StatusViaSLF4JLoggerFactory.java:20)
	at 	at ch.qos.logback.classic.servlet.LogbackServletContainerInitializer.onStartup(LogbackServletContainerInitializer.java:32)
	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5423)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at 	at java.lang.Thread.run(Thread.java:745)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.classic.net.SMTPAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	... 26 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/mail/internet/AddressException
	at 	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2595)
	at 	at java.lang.Class.getConstructor0(Class.java:2895)
	at 	at java.lang.Class.newInstance(Class.java:354)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:61)
	at 	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.mail.internet.AddressException
	at 	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
	at 	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
	at 	... 34 common frames omitted

```

**Comment by venusdrogon** [comment]
```XML

	<appender name="EMAIL" class="ch.qos.logback.classic.net.SMTPAppender">
		<smtpHost>smtp.163.com</smtpHost>
		<username>*******</username>
		<password>*******</password>

		<from>XiaoFei monitor&lt;feilongtestemail@163.com&gt;</from>
	 
		<!-- 多个收件人 以逗号分隔 或者多个to元素 -->
		<to>*******@163.com</to>

		<charsetEncoding>utf-8</charsetEncoding>

		<!-- <to>ANOTHER_EMAIL_DESTINATION</to> --> <!-- additional destinations are possible -->
		<subject>%-5level %logger{20} - %m</subject>

		<layout class="ch.qos.logback.classic.html.HTMLLayout">
			<pattern>%d{yyyy-MM-dd HH:mm:ss} %-5level \(%F:%L\) %method\(\) - %m%n</pattern>
		</layout>

		<!-- send just one log entry per email -->
		<!-- -->
		<!-- <cyclicBufferTracker class="ch.qos.logback.core.spi.CyclicBufferTracker">
			<bufferSize>1</bufferSize>
			</cyclicBufferTracker> -->

		<evaluator class="ch.qos.logback.classic.boolex.OnMarkerEvaluator">


		</evaluator>

	</appender>
	
	<logger name="com.feilong.controller.LogbackEmailController" level="info" additivity="false">
		<appender-ref ref="EMAIL" />
		<appender-ref ref="CONSOLE" />
	</logger>

```

**Comment by venusdrogon** [comment]
加入 依赖 

```XML
	<dependency>
			<groupId>com.feilong.platform.toolsextension</groupId>
			<artifactId>feilong-tools-mail</artifactId>
			<version>${version.feilong-platform}</version>
		</dependency>

```




```JAVA
03:11:30,043 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@677df38f - Adding [file:/Users/feilong/Development/DataCommon/Files/Java/config/commonlogback.xml] to configuration watch list.
03:11:30,048 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
03:11:30,069 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
03:11:33,086 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.net.SMTPAppender]
03:11:33,117 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [EMAIL]
03:11:37,048 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.feilong.controller.LogbackEmailController] to INFO
03:11:37,048 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.feilong.controller.LogbackEmailController] to false

```

**Comment by venusdrogon** [comment]
```jAVA

03:12:49,917 |-INFO in ch.qos.logback.classic.net.SMTPAppender[EMAIL] - SMTPAppender [EMAIL] is tracking [1] buffers
03:12:49 ERROR (LogbackEmailController.java:42) test1() - error
```

**Comment by venusdrogon** [comment]
```JAVA
 if (eventEvaluator.evaluate(eventObject)) {
                // clone the CyclicBuffer before sending out asynchronously
                CyclicBuffer<E> cbClone = new CyclicBuffer<E>(cb);
                // see http://jira.qos.ch/browse/LBCLASSIC-221
                cb.clear();
```


这里返回的是false


```XML


evaluator | IEvaluator | 

This option is declared by creating a new<EventEvaluator/> element. 

The name of the class that the user wishes to use as the SMTPAppender's Evaluatorneeds to be specified via the class attribute.In the absence of this option, SMTPAppender is assigned an instance of OnErrorEvaluator which triggers email transmission when it encounters an event of level ERROR or higher.Logback ships with several other evaluators, namely OnMarkerEvaluator (discussed below) and a powerful evaluator called JaninoEventEvaluator, discussed in another chapter. 

The more recent versions of logback ship with an even more powerful evaluator called GEventEvaluator.


-- | -- | --




```


默认 ch.qos.logback.classic.boolex.OnErrorEvaluator@5d38c43a

```
03:26:17 DEBUG (ServletRequestAttributeLoggingListener.java:67) attributeRemoved() - name:[encodingFilter.FILTERED],value:[true] removed from [servletRequest]
03:26:18,019 |-INFO in ch.qos.logback.classic.net.SMTPAppender[EMAIL] - About to send out SMTP message "ERROR c.f.c.LogbackEmailController - error" to [xin.jin@.com]
03:26:18 DEBUG (ServletRequestAttributeLoggingListener.java:67) attributeRemoved() - name:[encodingFilter.FILTERED],value:[true] removed from [servletRequest]
```


收到邮件了 

![image](https://user-images.githubusercontent.com/3479472/28891197-407f94f8-77fc-11e7-9a22-24d8d2fdf108.png)

**Comment by venusdrogon** [comment]
see 

https://logback.qos.ch/manual/appenders.html#SMTPAppender
http://blog.csdn.net/doraemon_wu/article/details/51972261
http://superich2008.iteye.com/blog/2070388

**Comment by venusdrogon** [comment]
准备写个文档
