### ISSUE TITLE
feilong-net-filetransfer 貌似在两个定时任务同时跑的情况下会出现异常

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-platform#22]
feilong-net-filetransfer 貌似在两个定时任务同时发跑的情况下会出现异常

``` JAVA

1011 15:20:00 ERROR (SysEmailExportManagerImpl.java:172) writeData() - 文件生成结果:0
1011 15:20:00 INFO  (SFTPFileTransfer.java:117) connect() - connect [sftp]:[true]
1011 15:20:00 INFO  (AbstractFileTransfer.java:141) checkOrMkdirs() - begin checkOrMkdirs remoteDirectory:[/upload_test/GW/08VIP/]
1011 15:20:01 INFO  (SFTPFileTransfer.java:117) connect() - connect [sftp]:[true]
1011 15:20:01 INFO  (AbstractFileTransfer.java:391) downloadDontClose() - remotePath:/upload_test/GW/08VIP/Staff_20161011.CSV will be download to filePath:/home/vmuser/staff_backup_gw/Staff_20161011.CSV 
1011 15:20:01 INFO  (SFTPFileTransfer.java:117) connect() - connect [sftp]:[true]
1011 15:20:01 INFO  (AbstractFileTransfer.java:141) checkOrMkdirs() - begin checkOrMkdirs remoteDirectory:[/upload_test/GW/08VIP/]
1011 15:20:01 WARN  (AbstractFileTransfer.java:146) checkOrMkdirs() - can't cd:[/upload_test/GW/08VIP/],cause by:[],will try [mkdirs]~~
1011 15:20:01 ERROR (SFTPFileTransfer.java:308) downRemoteSingleFile() - 
com.jcraft.jsch.SftpException: RequestQueue: unknown request id 1852055663
    at com.jcraft.jsch.ChannelSftp$RequestQueue.get(ChannelSftp.java:1220)
    at com.jcraft.jsch.ChannelSftp._get(ChannelSftp.java:1068)
    at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:1006)
    at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:984)
    at com.feilong.tools.net.filetransfer.sftp.SFTPFileTransfer.downRemoteSingleFile(SFTPFileTransfer.java:305)
    at com.feilong.tools.net.filetransfer.AbstractFileTransfer.downloadDontClose(AbstractFileTransfer.java:392)
    at com.feilong.tools.net.filetransfer.AbstractFileTransfer.download(AbstractFileTransfer.java:86)
    at com.store.manager.member.impl.StaffMemberImportManagerImpl.importStaffDate(StaffMemberImportManagerImpl.java:110)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy527.importStaffDate(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
    at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:312)
    at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:203)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:520)
1011 15:20:01 INFO  (StaffMemberImportManagerImpl.java:123) importStaffDate() - Exception:
com.feilong.tools.net.filetransfer.FileTransferException: 4: RequestQueue: unknown request id 1852055663
    at com.feilong.tools.net.filetransfer.sftp.SFTPFileTransfer.downRemoteSingleFile(SFTPFileTransfer.java:309)
    at com.feilong.tools.net.filetransfer.AbstractFileTransfer.downloadDontClose(AbstractFileTransfer.java:392)
    at com.feilong.tools.net.filetransfer.AbstractFileTransfer.download(AbstractFileTransfer.java:86)
    at com.store.manager.member.impl.StaffMemberImportManagerImpl.importStaffDate(StaffMemberImportManagerImpl.java:110)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy527.importStaffDate(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
    at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:312)
    at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:203)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:520)
Caused by: com.jcraft.jsch.SftpException: RequestQueue: unknown request id 1852055663
    at com.jcraft.jsch.ChannelSftp$RequestQueue.get(ChannelSftp.java:1220)
    at com.jcraft.jsch.ChannelSftp._get(ChannelSftp.java:1068)
    at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:1006)
    at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:984)
    at com.feilong.tools.net.filetransfer.sftp.SFTPFileTransfer.downRemoteSingleFile(SFTPFileTransfer.java:305)
    ... 25 common frames omitted

```

**Comment by venusdrogon** [comment]
多线程或者多job同时跑的情况

spring xml 配置加上 `scope="prototype"`

**示例代码:**

``` JAVA

    <!-- sftp -->
    <bean id="sftpFileTransfer" class="com.feilong.tools.net.filetransfer.sftp.SFTPFileTransfer" scope="prototype">
        <property name="sftpFileTransferConfig">
            <bean class="com.feilong.tools.net.filetransfer.sftp.SFTPFileTransferConfig">
                <property name="hostName" value="#{p_sftp['fileTransfer.sftp.hostName']}" />
                <property name="userName" value="#{p_sftp['fileTransfer.sftp.userName']}" />
                <property name="password">
                    <value><![CDATA[#{p_sftp['fileTransfer.sftp.password']}]]></value>
                </property>
                <property name="port" value="#{p_sftp['fileTransfer.sftp.port']}" />

                <property name="sessionTimeout" value="#{p_sftp['fileTransfer.sftp.sessionTimeout']}" />
                <property name="sshConfig" ref="p_sftp-sshConfig" />
            </bean>
        </property>
    </bean>

```

**说明:**

![image](https://cloud.githubusercontent.com/assets/3479472/19266172/e3d2efb6-8fda-11e6-9bbf-76d813c10bde.png)

**Comment by venusdrogon** [comment]
测试场景:模拟 两个定时任务 

## 1.服务类

两个业务类,分别下载不同的文件

**MutiSFTPFileTransferDownloadServer1**

``` JAVA

public class MutiSFTPFileTransferDownloadServer1{

    private static final Logger LOGGER = LoggerFactory.getLogger(MutiSFTPFileTransferDownloadServer1.class);


    @Autowired
    @Qualifier("sftpFileTransfer")
    private FileTransfer        fileTransfer;

    @Test
    public void downloadFile(){
        LOGGER.info("begin mutiSFTPFileTransferDownloadTest1");
        String[] remotePaths = {
                                 "/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML" };
        String localAbsoluteDirectoryPath = "E:\\test\\1";
        fileTransfer.download(localAbsoluteDirectoryPath, remotePaths);

        LOGGER.info("end mutiSFTPFileTransferDownloadTest1");
    }
}

```

**MutiSFTPFileTransferDownloadServer2**

``` JAVA

public class MutiSFTPFileTransferDownloadServer2{

    private static final Logger LOGGER = LoggerFactory.getLogger(MutiSFTPFileTransferDownloadServer2.class);

    @Autowired
    @Qualifier("sftpFileTransfer")
    private FileTransfer        fileTransfer;

    @Test
    public void downloadFile(){
        LOGGER.info("begin mutiSFTPFileTransferDownloadTest1");
        String[] remotePaths = {
                                 "/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML" };
        String localAbsoluteDirectoryPath = "E:\\test\\1";
        fileTransfer.download(localAbsoluteDirectoryPath, remotePaths);
        LOGGER.info("end mutiSFTPFileTransferDownloadTest1");
    }

}
```

加入配置

``` XML
    <bean class="com.feilong.tools.net.filetransfer.MutiSFTPFileTransferDownloadServer1" />
    <bean class="com.feilong.tools.net.filetransfer.MutiSFTPFileTransferDownloadServer2" />
```

## 2. 测试类

两个定时任务, 每两秒执行一次

``` JAVA

public class MutiTest extends AbstractFileTransferTest{

    @Autowired
    private MutiSFTPFileTransferDownloadServer1 mutiSFTPFileTransferDownloadTest1;

    @Autowired
    private MutiSFTPFileTransferDownloadServer2 mutiSFTPFileTransferDownloadTest2;

    @Test
    public void testMutiTest() throws InterruptedException{

        addTimerTask(new TimerTask(){

            @Override
            public void run(){
                mutiSFTPFileTransferDownloadTest1.downloadFile();
            }
        });

        addTimerTask(new TimerTask(){

            @Override
            public void run(){
                mutiSFTPFileTransferDownloadTest2.downloadFile();
            }
        });

        //睡眠5分钟
        Thread.sleep(MILLISECOND_PER_MINUTE * 5);
    }

    private void addTimerTask(TimerTask timerTask){
        Timer timer = new Timer();

        //delay 行任务前的延迟时间，单位是毫秒。
        //period - 执行各后续任务之间的时间间隔，单位是毫秒。 
        timer.schedule(timerTask, 2L, MILLISECOND_PER_SECONDS * 2);
    }

}


```

## 3.Singleton 测试结果

当 SFTPFileTransfer 是默认或者是  Singleton 的时候, 启动

会出现以下的异常 

``` JAVA

11:15:20 DEBUG (SFTPUtil.java:59) [connectSession()] will use [sftpFileTransferConfig]:[    {
        "port": 22,
        "sshConfig": {"StrictHostKeyChecking": "no"},
        "userName": "speedo",
        "hostName": "10.11.54.21",
        "password": "******",
        "sessionTimeout": 50000
    }] to create session
11:15:20 DEBUG (SFTPUtil.java:75) [connectSession()] -------------session connecting......-------------
11:15:20 DEBUG (SFTPUtil.java:75) [connectSession()] -------------session connecting......-------------
11:15:21 DEBUG (SFTPFileTransfer.java:110) [connect()] open [sftp] session channel...
11:15:21 DEBUG (SFTPFileTransfer.java:110) [connect()] open [sftp] session channel...
11:15:21 DEBUG (SFTPFileTransfer.java:113) [connect()] channel connecting...
11:15:21 DEBUG (SFTPFileTransfer.java:113) [connect()] channel connecting...
11:15:21 INFO  (SFTPFileTransfer.java:117) [connect()] success connect [sftp]
11:15:21 INFO  (SFTPFileTransfer.java:117) [connect()] success connect [sftp]
11:15:21 ERROR (SFTPFileTransfer.java:262) [isDirectory()] remoteFile:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML]
4: 
    at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2235)
    at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2242)
    at com.jcraft.jsch.ChannelSftp.stat(ChannelSftp.java:2199)
    at com.feilong.tools.net.filetransfer.sftp.SFTPFileTransfer.isDirectory(SFTPFileTransfer.java:256)
    at com.feilong.tools.net.filetransfer.AbstractFileTransfer.downloadDontClose(AbstractFileTransfer.java:361)
    at com.feilong.tools.net.filetransfer.AbstractFileTransfer.download(AbstractFileTransfer.java:68)
    at com.feilong.tools.net.filetransfer.MutiSFTPFileTransferDownloadServer1.downloadFile(MutiSFTPFileTransferDownloadServer1.java:40)
    at com.feilong.tools.net.filetransfer.MutiTest$1.run(MutiTest.java:42)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: inputstream is closed
    at com.jcraft.jsch.ChannelSftp.fill(ChannelSftp.java:2911)
    at com.jcraft.jsch.ChannelSftp.header(ChannelSftp.java:2935)
    at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2216)
    ... 9 more
11:15:21 ERROR (SFTPFileTransfer.java:262) [isDirectory()] remoteFile:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML]
4: 
    at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2235)
    at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2242)
    at com.jcraft.jsch.ChannelSftp.stat(ChannelSftp.java:2199)
    at com.feilong.tools.net.filetransfer.sftp.SFTPFileTransfer.isDirectory(SFTPFileTransfer.java:256)
    at com.feilong.tools.net.filetransfer.AbstractFileTransfer.downloadDontClose(AbstractFileTransfer.java:361)
    at com.feilong.tools.net.filetransfer.AbstractFileTransfer.download(AbstractFileTransfer.java:68)
    at com.feilong.tools.net.filetransfer.MutiSFTPFileTransferDownloadServer2.downloadFile(MutiSFTPFileTransferDownloadServer2.java:40)
    at com.feilong.tools.net.filetransfer.MutiTest$2.run(MutiTest.java:50)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: inputstream is closed
    at com.jcraft.jsch.ChannelSftp.fill(ChannelSftp.java:2911)
    at com.jcraft.jsch.ChannelSftp.header(ChannelSftp.java:2935)
    at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2216)
    ... 9 more


```

## 4. prototype测试结果

当在 spring 的配置文件中, 加入  `scope="prototype"`

比如

``` XML

<bean id="sftpFileTransfer" class="com.feilong.tools.net.filetransfer.sftp.SFTPFileTransfer" scope="prototype">

...

</bean>

```

运行结果:

``` JAVA

11:19:47 INFO  (TestContextManager.java:235) [retrieveTestExecutionListeners()] Could not instantiate TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [javax/servlet/ServletContext]
11:19:47 INFO  (XmlBeanDefinitionReader.java:316) [loadBeanDefinitions()] Loading XML bean definitions from URL [file:/E:/Workspaces/feilong/feilong-tools/feilong-net-filetransfer/target/test-classes/spring/spring-fileTransfer.xml]
11:19:47 INFO  (AbstractApplicationContext.java:515) [prepareRefresh()] Refreshing org.springframework.context.support.GenericApplicationContext@2371c0: startup date [Wed Oct 12 11:19:47 CST 2016]; root of context hierarchy
11:19:48 INFO  (PropertiesLoaderSupport.java:172) [loadProperties()] Loading properties file from URL [file:E:/DataCommon/Files/Java/config/fileTransfer-ftp.properties]
11:19:48 INFO  (PropertiesLoaderSupport.java:172) [loadProperties()] Loading properties file from URL [file:E:/DataCommon/Files/Java/config/fileTransfer-sftp.properties]
11:19:48 INFO  (PropertiesLoaderSupport.java:172) [loadProperties()] Loading properties file from class path resource [config/fileTransfer-sftp-sshConfig.properties]
11:19:48 INFO  (MutiSFTPFileTransferDownloadServer2.java:36) [downloadFile()] begin mutiSFTPFileTransferDownloadTest1
11:19:48 INFO  (MutiSFTPFileTransferDownloadServer1.java:36) [downloadFile()] begin mutiSFTPFileTransferDownloadTest1
11:19:48 DEBUG (SFTPUtil.java:59) [connectSession()] will use [sftpFileTransferConfig]:[    {
        "port": 22,
        "sshConfig": {"StrictHostKeyChecking": "no"},
        "userName": "speedo",
        "hostName": "10.11.54.21",
        "password": "******",
        "sessionTimeout": 50000
    }] to create session
11:19:48 DEBUG (SFTPUtil.java:59) [connectSession()] will use [sftpFileTransferConfig]:[    {
        "port": 22,
        "sshConfig": {"StrictHostKeyChecking": "no"},
        "userName": "speedo",
        "hostName": "10.11.54.21",
        "password": "******",
        "sessionTimeout": 50000
    }] to create session
11:19:48 DEBUG (SFTPUtil.java:75) [connectSession()] -------------session connecting......-------------
11:19:48 DEBUG (SFTPUtil.java:75) [connectSession()] -------------session connecting......-------------
11:19:49 DEBUG (SFTPFileTransfer.java:110) [connect()] open [sftp] session channel...
11:19:49 DEBUG (SFTPFileTransfer.java:110) [connect()] open [sftp] session channel...
11:19:49 DEBUG (SFTPFileTransfer.java:113) [connect()] channel connecting...
11:19:49 DEBUG (SFTPFileTransfer.java:113) [connect()] channel connecting...
11:19:49 INFO  (SFTPFileTransfer.java:117) [connect()] success connect [sftp]
11:19:49 DEBUG (SFTPFileTransfer.java:258) [isDirectory()] remoteFile:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] is [file]
11:19:49 INFO  (AbstractFileTransfer.java:374) [downloadDontClose()] remotePath:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] will be download to [E:\test\1/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML]
11:19:49 DEBUG (FileUtil.java:362) [createDirectory()] directory:[E:\test\1] exists,don't need mkdirs,nothing to do~
11:19:49 INFO  (SFTPFileTransfer.java:134) [disconnect()] ---------------channelSftp exit....---------------
11:19:49 INFO  (SFTPFileTransfer.java:138) [disconnect()] --------------session disconnect....--------------
11:19:49 INFO  (MutiSFTPFileTransferDownloadServer1.java:42) [downloadFile()] end mutiSFTPFileTransferDownloadTest1
11:19:49 INFO  (SFTPFileTransfer.java:117) [connect()] success connect [sftp]
11:19:49 DEBUG (SFTPFileTransfer.java:258) [isDirectory()] remoteFile:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] is [file]
11:19:49 INFO  (AbstractFileTransfer.java:374) [downloadDontClose()] remotePath:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] will be download to [E:\test\1/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML]
11:19:49 DEBUG (FileUtil.java:362) [createDirectory()] directory:[E:\test\1] exists,don't need mkdirs,nothing to do~
11:19:49 INFO  (SFTPFileTransfer.java:134) [disconnect()] ---------------channelSftp exit....---------------
11:19:49 INFO  (SFTPFileTransfer.java:138) [disconnect()] --------------session disconnect....--------------
11:19:49 INFO  (MutiSFTPFileTransferDownloadServer2.java:41) [downloadFile()] end mutiSFTPFileTransferDownloadTest1
11:19:50 INFO  (MutiSFTPFileTransferDownloadServer2.java:36) [downloadFile()] begin mutiSFTPFileTransferDownloadTest1
11:19:50 DEBUG (SFTPUtil.java:59) [connectSession()] will use [sftpFileTransferConfig]:[    {
        "port": 22,
        "sshConfig": {"StrictHostKeyChecking": "no"},
        "userName": "speedo",
        "hostName": "10.11.54.21",
        "password": "******",
        "sessionTimeout": 50000
    }] to create session
11:19:50 DEBUG (SFTPUtil.java:75) [connectSession()] -------------session connecting......-------------
11:19:50 INFO  (MutiSFTPFileTransferDownloadServer1.java:36) [downloadFile()] begin mutiSFTPFileTransferDownloadTest1
11:19:50 DEBUG (SFTPUtil.java:59) [connectSession()] will use [sftpFileTransferConfig]:[    {
        "port": 22,
        "sshConfig": {"StrictHostKeyChecking": "no"},
        "userName": "speedo",
        "hostName": "10.11.54.21",
        "password": "******",
        "sessionTimeout": 50000
    }] to create session
11:19:50 DEBUG (SFTPUtil.java:75) [connectSession()] -------------session connecting......-------------
11:19:50 DEBUG (SFTPFileTransfer.java:110) [connect()] open [sftp] session channel...
11:19:50 DEBUG (SFTPFileTransfer.java:113) [connect()] channel connecting...
11:19:50 DEBUG (SFTPFileTransfer.java:110) [connect()] open [sftp] session channel...
11:19:50 DEBUG (SFTPFileTransfer.java:113) [connect()] channel connecting...
11:19:50 INFO  (SFTPFileTransfer.java:117) [connect()] success connect [sftp]
11:19:50 DEBUG (SFTPFileTransfer.java:258) [isDirectory()] remoteFile:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] is [file]
11:19:50 INFO  (AbstractFileTransfer.java:374) [downloadDontClose()] remotePath:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] will be download to [E:\test\1/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML]
11:19:50 DEBUG (FileUtil.java:362) [createDirectory()] directory:[E:\test\1] exists,don't need mkdirs,nothing to do~
11:19:50 INFO  (SFTPFileTransfer.java:117) [connect()] success connect [sftp]
11:19:50 DEBUG (SFTPFileTransfer.java:258) [isDirectory()] remoteFile:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] is [file]
11:19:50 INFO  (AbstractFileTransfer.java:374) [downloadDontClose()] remotePath:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] will be download to [E:\test\1/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML]
11:19:50 DEBUG (FileUtil.java:362) [createDirectory()] directory:[E:\test\1] exists,don't need mkdirs,nothing to do~
11:19:50 INFO  (SFTPFileTransfer.java:134) [disconnect()] ---------------channelSftp exit....---------------
11:19:50 INFO  (SFTPFileTransfer.java:138) [disconnect()] --------------session disconnect....--------------
11:19:50 INFO  (MutiSFTPFileTransferDownloadServer2.java:41) [downloadFile()] end mutiSFTPFileTransferDownloadTest1
11:19:50 INFO  (SFTPFileTransfer.java:134) [disconnect()] ---------------channelSftp exit....---------------
11:19:50 INFO  (SFTPFileTransfer.java:138) [disconnect()] --------------session disconnect....--------------
11:19:50 INFO  (MutiSFTPFileTransferDownloadServer1.java:42) [downloadFile()] end mutiSFTPFileTransferDownloadTest1
11:19:52 INFO  (MutiSFTPFileTransferDownloadServer2.java:36) [downloadFile()] begin mutiSFTPFileTransferDownloadTest1
11:19:52 DEBUG (SFTPUtil.java:59) [connectSession()] will use [sftpFileTransferConfig]:[    {
        "port": 22,
        "sshConfig": {"StrictHostKeyChecking": "no"},
        "userName": "speedo",
        "hostName": "10.11.54.21",
        "password": "******",
        "sessionTimeout": 50000
    }] to create session
11:19:52 DEBUG (SFTPUtil.java:75) [connectSession()] -------------session connecting......-------------
11:19:52 INFO  (MutiSFTPFileTransferDownloadServer1.java:36) [downloadFile()] begin mutiSFTPFileTransferDownloadTest1
11:19:52 DEBUG (SFTPUtil.java:59) [connectSession()] will use [sftpFileTransferConfig]:[    {
        "port": 22,
        "sshConfig": {"StrictHostKeyChecking": "no"},
        "password": "******",
        "sessionTimeout": 50000
    }] to create session
11:19:52 DEBUG (SFTPUtil.java:75) [connectSession()] -------------session connecting......-------------
11:19:52 DEBUG (SFTPFileTransfer.java:110) [connect()] open [sftp] session channel...
11:19:52 DEBUG (SFTPFileTransfer.java:113) [connect()] channel connecting...
11:19:52 DEBUG (SFTPFileTransfer.java:110) [connect()] open [sftp] session channel...
11:19:52 DEBUG (SFTPFileTransfer.java:113) [connect()] channel connecting...
11:19:52 INFO  (SFTPFileTransfer.java:117) [connect()] success connect [sftp]
11:19:52 DEBUG (SFTPFileTransfer.java:258) [isDirectory()] remoteFile:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] is [file]
11:19:52 INFO  (AbstractFileTransfer.java:374) [downloadDontClose()] remotePath:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] will be download to [E:\test\1/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML]
11:19:52 DEBUG (FileUtil.java:362) [createDirectory()] directory:[E:\test\1] exists,don't need mkdirs,nothing to do~
11:19:52 INFO  (SFTPFileTransfer.java:117) [connect()] success connect [sftp]
11:19:52 DEBUG (SFTPFileTransfer.java:258) [isDirectory()] remoteFile:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] is [file]
11:19:52 INFO  (AbstractFileTransfer.java:374) [downloadDontClose()] remotePath:[/upload/Inbound/InventoryAdjustments/Archive/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML] will be download to [E:\test\1/2016-07-15_11-58-58.389-INVENTORY_ADJUSTMENTS_3PL_20160715-154626-073.XML]
11:19:52 DEBUG (FileUtil.java:362) [createDirectory()] directory:[E:\test\1] exists,don't need mkdirs,nothing to do~
11:19:52 INFO  (SFTPFileTransfer.java:134) [disconnect()] ---------------channelSftp exit....---------------
11:19:52 INFO  (SFTPFileTransfer.java:138) [disconnect()] --------------session disconnect....--------------
11:19:52 INFO  (MutiSFTPFileTransferDownloadServer1.java:42) [downloadFile()] end mutiSFTPFileTransferDownloadTest1
11:19:52 INFO  (SFTPFileTransfer.java:134) [disconnect()] ---------------channelSftp exit....---------------
11:19:52 INFO  (SFTPFileTransfer.java:138) [disconnect()] --------------session disconnect....--------------
11:19:52 INFO  (MutiSFTPFileTransferDownloadServer2.java:41) [downloadFile()] end mutiSFTPFileTransferDownloadTest1

```

很正常

## 5.结论

sftpFileTransfer 是有状态的, 建议加上  `scope="prototype"`

**Comment by venusdrogon** [comment]
感谢 从果同学发现的问题
