### ISSUE TITLE
修改 SFTPFileTransfer 日志和异常体系

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-platform#81]
修改 SFTPFileTransfer 日志和异常体系

```JAVA

	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:520)
Caused by: com.feilong.tools.net.filetransfer.FileTransferException: sftpFileTransferConfig:    {
        "port": 22,
        "sshConfig": {"StrictHostKeyChecking": "no"},
        "userName": "****",
        "hostName": "*******",
        "password": "******",
        "sessionTimeout": 50000
    },by:java.lang.ArrayIndexOutOfBoundsException
	at com.feilong.tools.net.filetransfer.sftp.SFTPFileTransfer.connect(SFTPFileTransfer.java:122)
	at com.feilong.tools.net.filetransfer.AbstractFileTransfer.download(AbstractFileTransfer.java:64)

```

**Comment by venusdrogon** [comment]
```JAVA

com.jcraft.jsch.SftpException: 
	at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2208)
	at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2215)
	at com.jcraft.jsch.ChannelSftp.stat(ChannelSftp.java:2172)
	at com.feilong.tools.net.filetransfer.sftp.SFTPFileTransfer.isDirectory(SFTPFileTransfer.java:263)
	at com.feilong.tools.net.filetransfer.AbstractFileTransfer.downloadDontClose(AbstractFileTransfer.java:364)
	at com.feilong.tools.net.filetransfer.AbstractFileTransfer.download(AbstractFileTransfer.java:67)
	at com.store.handler.ami.file.SyncArticleMasterFileHandlerImpl.syncArticleMasterToLocal(SyncArticleMasterFileHandlerImpl.java:90)
	at sun.reflect.GeneratedMethodAccessor273.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy609.syncArticleMasterToLocal(Unknown Source)
	at com.store.manager.ami.sync.artical.SyncUpdateArticleMasterManagerImpl.syncArticleMasterUpdate(SyncUpdateArticleMasterManagerImpl.java:64)
	at sun.reflect.GeneratedMethodAccessor282.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:312)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:203)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:520)
Caused by: java.lang.NullPointerException: null
	at com.jcraft.jsch.ChannelSftp.sendPacketPath(ChannelSftp.java:2562)
	at com.jcraft.jsch.ChannelSftp.sendPacketPath(ChannelSftp.java:2559)
	at com.jcraft.jsch.ChannelSftp.sendSTAT(ChannelSftp.java:2479)
	at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2186)
	... 27 common frames omitted

```

**Comment by venusdrogon** [comment]
修改 

```JAVA

public final class FileTransferException extends RuntimeException{

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = -1699987643831455524L;

    //---------------------------------------------------------------

    /**
     * The Constructor.
     *
     * @param messagePattern
     *            the message pattern
     * @param args
     *            the args
     */
    public FileTransferException(String messagePattern, Object...args){
        super(Slf4jUtil.format(messagePattern, args));
    }

    /**
     * The Constructor.
     *
     * @param message
     *            the message
     * @param cause
     *            the cause
     */
    public FileTransferException(String message, Throwable cause){
        super(buildMessage(message, cause), cause);
    }

    //---------------------------------------------------------------

    /**
     * Builds the message.
     *
     * @param message
     *            the message
     * @param cause
     *            the cause
     * @return the string
     * @since 1.10.4
     */
    private static String buildMessage(String message,Throwable cause){
        if (null == message){
            return cause.getMessage();
        }
        return message + ",error message:[" + cause.getMessage() + "]";
    }
}


```
